### ISSUE TITLE
Zahlen und Text teils abgeschnitten

### ISSUE THREAD

**Issue by Mihahn** [MacSchierer/ImpfQuoten#1]
Leider sind die Zahlen und der Text teilweise abgeschnitten; ggf. könnte dort die Schriftgröße angepasst werden? Bzw. über Parameter für verschiedene Gerätegrößen gelöst werden?

![IMG_0261](https://user-images.githubusercontent.com/3447340/121567407-d10c3580-ca1e-11eb-8dda-15142a50d550.jpg)

Vielen Dank für das schöne Widget!

**Comment by MacSchierer** [comment]
Hi Mihahn,
freut mich, wenn dir das Witget gefällt. Auf welchem iOS Gerät hast du es am laufen?

**Comment by Mihahn** [comment]
Auf einem iPhone 7 (iOS 14.7 beta) und auf einem iPad 6 (9,7"; iPadOS 15 beta); bei beiden ist etwas abgeschnitten.

**Comment by MacSchierer** [comment]
Leider kann ich das Widget nicht entsprechend testen, da ich weder die Geräte noch die Betaversionen verwende. 
Vielleicht versuchst du einfach mal die Schriftgröße im Skript anzupassen.

Beispiel:

TitleText.font = Font.boldSystemFont(12)

TitleText.minimumScaleFactor = 0.5

**Comment by Mihahn** [comment]
Danke dir für den Support! Ich habe jetzt die Werte in den folgenden Zeilen geändert und es passt:

Bei dem Text der Erst- und Zweitimpfungen:
`let Title1stText = Stack1Head.addText("Erstimpfung")`
					`Title1stText.textColor = MainTextColor`
					`Title1stText.font = Font.boldSystemFont(12)`
					`Title1stText.minimumScaleFactor = 0.5`

`let Title2ndText = Stack2Head.addText("Zweitimpfung")`
						`Title2ndText.textColor = MainTextColor`
						`Title2ndText.font = Font.boldSystemFont(12)`

Das Wichtigste waren aber die Prozente (28 auf 20), also:
`Quote1stText.font = Font.boldSystemFont(20)`
`Quote2ndText.font = Font.boldSystemFont(20)`

Nochmals vielen Dank! Jetzt passt es besser zur Gerätegröße 👍
