### ISSUE TITLE
Keine Daten

### ISSUE THREAD

**Issue by UweLoyal** [MacSchierer/ImpfQuoten#3]
Script erhält seit einigen Tagen keine Daten mehr!
Datenverarbeitungsfehler

LG
UweL

**Comment by MacSchierer** [comment]
Hallo Uwe,
so wie es aussah, lieferte die "API" (https://github.com/ThisIsBenny/rki-vaccination-data) in den letzten Tagen keine Daten.
Die "API" wurde gestern angepasst und das Skript läuft wieder.

Grüße
 Stefan
